---

- name: Wait for kibana startup...
  wait_for_connection:
    delay: 120
    timeout: 300
- name: "Unlock RO index"
  uri:
    url: "http://{{kibana_server_ip}}:9200/_all/_settings"
    method: PUT
    user: "{{ kibana_user }}"
    password: "{{ kibana_password }}"
    force_basic_auth: yes
    body: "{\"index.blocks.read_only_allow_delete\": null}"
    headers:
      Content-Type: "application/json; charset=utf-8"

- name: "Create index oio-*"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/index-pattern"
    method: POST
    user: "{{ kibana_user }}"
    password: "{{ kibana_password }}"
    body: "{{ '{\"attributes\": {\"title\": \"'+ kibana_index_pattern +'\", \"timeFieldName\": \"'+ kibana_time_filter +'\"}}' }}"
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana
  register: index
  no_log: True

- name: Extract index id and type
  set_fact:
    id: "{{ index.json.id }}"
    type: "{{ index.json.type }}"
  register: bulk_get
  no_log: True

- name: "POST bulk get"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/bulk_get"
    method: POST
    user: "{{ kibana_user }}"
    password: "{{ kibana_password }}"
    body: "[{{ bulk_get.ansible_facts }}]"
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana

- set_fact:
    value: "{{ id }}"
  register: dict_value
  no_log: True
- name: "Make the oio-* as the defaul index"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/kibana/settings/defaultIndex"
    method: POST
    user: "{{ kibana_user }}"
    password: "{{ kibana_password }}"
    body: "{{ dict_value.ansible_facts }}"
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana
  no_log: True
- name: "PUT the index pattern"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/index-pattern/{{ id}}"
    method: PUT
    user: "{{ kibana_user }}"
    password: "{{ kibana_password }}"
    body: "{{ '{\"attributes\": {\"title\": \"'+ kibana_index_pattern +'\", \"timeFieldName\": \"'+ kibana_time_filter +'\"}}' }}"
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana
