---
- name: Wait until kibana is up  !!!!!
  wait_for:
    host: "{{kibana_server_ip}}"
    port: 5601
    delay: 10

- name: "Create index oio-*"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/index-pattern"
    method: POST
    body: "{{ '{\"attributes\": {\"title\": \"'+ kibana_index_pattern +'\", \"timeFieldName\": \"'+ kibana_time_filter +'\"}}' }}"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana
  register: index


- name: Extract index id and type
  set_fact:
    id: "{{ index.json.id }}"
    type: "{{ index.json.type }}"
  register: bulk_get


- name: "POST bulk get"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/bulk_get"
    method: POST
    body: "[{{ bulk_get.ansible_facts }}]"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana

- set_fact:
    value: "{{ id }}"
  register: dict_value

- name: "Make the oio-* as the defaul index"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/kibana/settings/defaultIndex"
    method: POST
    body: "{{ dict_value.ansible_facts }}"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana

- name: "PUT the index pattern"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/index-pattern/{{ id}}"
    method: PUT
    body: "{{ '{\"attributes\": {\"title\": \"'+ kibana_index_pattern +'\", \"timeFieldName\": \"'+ kibana_time_filter +'\"}}' }}"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana

# ********* import dashboard *****************************

- name: Extract all _id
  set_fact:
    item_id: "{{ item._id }}"
  with_items: "{{ kibana_dashboard }}"
  register: dict_id

- name: Extract all _source
  set_fact:
    attributes: "{{ item._source }}"
  with_items: "{{ kibana_dashboard }}"
  register: dict_attributes

- name: Create a list of  attributes
  set_fact:
      list_attributes: "{{dict_attributes.results | map(attribute='ansible_facts') | list }}"
      list_id: "{{ dict_id.results | map(attribute='ansible_facts.item_id') | list }}"


- name: "Import kibana's dashboard "
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/dashboard/{{ item.0 }}?overwrite=true"
    method: POST
    body: "{{ item.1 }}"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana
  with_together:
      - "{{ list_id }}"
      - "{{ list_attributes }}"

# ********* import visualization *****************************

- name: Get old index_id
  set_fact:
    attributes: "{{ item._source }}"
  with_items: "{{ kibana_visualization }}"
  register: source


- set_fact:
      sources_list: "{{source.results | map(attribute='ansible_facts') | list }}"
- set_fact:
    searchSourceJSON: "{{ sources_list[0].attributes.kibanaSavedObjectMeta.searchSourceJSON }}"
  register: sourceJSON

- set_fact:
    old_index_id: "{{ sourceJSON.ansible_facts.searchSourceJSON.index }}"


- name: Replace the old index_id to a new  index_id
  replace:
      path: "{{ kibana_visualization_path }}"
      regexp: "{{old_index_id}}"
      replace: "{{id}}"


- name: Extract all _id
  set_fact:
    item_id: "{{ item._id }}"
  with_items: "{{ kibana_visualization }}"
  register: dict_id


- name: Extract all _source
  set_fact:
    attributes: "{{ item._source }}"
  with_items: "{{ kibana_visualization }}"
  register: dict_attributes

- name: Create a list of  attributes
  set_fact:
      list_attributes: "{{dict_attributes.results | map(attribute='ansible_facts') | list }}"
      list_id: "{{ dict_id.results | map(attribute='ansible_facts.item_id') | list }}"


- name: "POST bulk get"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/bulk_get"
    method: POST
    body: '[{"id": "25eb9c90-4213-11e8-8c1f-edc7dd6da6be", "type": "index-pattern"}]'
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana


- name: "Import kibana's visualization"
  uri:
    url: "http://{{kibana_server_ip}}:5601/api/saved_objects/visualization/{{ item.0 }}?overwrite=true"
    method: POST
    body: "{{ item.1 }}"
    body_format: json
    headers:
      Content-Type: "application/json; charset=utf-8"
      Kbn-xsrf: kibana
  with_together:
      - "{{ list_id }}"
      - "{{ list_attributes }}"
...
